---
title: "Plan experimental (PLEX)"
author:
  - "Flavio Lozano-Isla $^{1*}$"
  - "$^{1}$ Agr. MSc, E-mail: flavjack@gmail.com"
date: "`r if (knitr:::is_html_output()) format(Sys.time(), '%d %b %Y %X')`"
description: Plan experimental
github-repo: flavjack/plex/issues
favicon: img/icon.png
site: bookdown::bookdown_site
documentclass: book
bookdown::gitbook:
output:
  bookdown::word_document2:
    reference_docx: cnfg/style_article.docx
always_allow_html: yes
link-citations: true
colorlinks: yes
bibliography: [cnfg/book.bib, cnfg/pkgs.bib]
csl: https://www.zotero.org/styles/iica-catie
---

```{r dataset, eval=FALSE, include=FALSE}
# source("cnfg/debug.r")
source("cnfg/setup.r")

sheets_auth(T)
url <- ""
gs <- as_sheets_id(url)
# browseURL(url)

```

# Introducción

Antes de iniciar a escribir algun proyecto de investigación deberia tomar estas recomendaciones para estructurar tú plan experimental, este documento esta basado en @kamoun2013GOHREP.

Recuerda que este documento es una recomendación en el planeamiento incial de un trabajo de investigación y puede servir como base para el desarrollo de una idea experimental.

# Estructura 

Un plan experimental debe contener como mínimo la siguiente estrúctura. Inicialmente para la formulación de la idea no es necesario incluir ninguna referencia y puede ser escrita con tus propias palabras e ideas. A medida que la idea se va tornando más estructurada se puede ir incluyendo referencias para sustentar la idea.

## Meta

El objetivo principal del trabajo, debe ser escrita como un título provisional de la investigación. 

## Hipótesis

Es la pregunta de investigación escrita en un parrafo, la cual debe ser redactada como una pregunta o como una afirmación.

## Fundamento

Escribir los fundamento que sustentan la viabilidad de la idea. Pueden ser las razones lógicas para sostener la idea, posteriormente se puede sustentar con documentos o artículos cientificos introducidas en forma de cita.

## Objetivos 

Las acciones o pasos para llegar al cumplimiento de la meta. Deber ser escrita en forma de acción. (ie. Se evaluará..., Se estimará..., Se realizaran..., etc)

## Plan experimental

Inicialmente puede ser un bosquejo de como se llevará acabo el trabajo de investigación. Esto será la base para el desarrollo de los Materiales y Métodos del trabajo de investigación.

# Base para un proyecto de investigación

Luego del desarrollo de los puntos mencionados en la estructura del plan experimental, se tendra una idea de como se estructurará el plan de trabajo, las cuales pueden posteriormente plasmarse en un proyecto de investigación.








