# Introducción {-}

```{block, echo = T, type='rmd-warning'}

<!-- caution - important - note - tip - warning -->

Antes de iniciar a leer este manuscrito, si tienes alguna duda o sugerencia no dejes de escribirme a mi correo: flavjack@gmail.com. Disculpen por los errores ortográficos, los cuales ire corrigiendo a medida que vaya avanzando el documento,  primero deseo que las ideas fluyan. Mencionar tambien que lo estoy escribiendo por la consola en R por lo que no es fácil acceder al corrector ortográfico :), gracias por su comprensión. Voy asustituir la "Ñ" por la "NH" por que los teclados alemanes no posee ese carácter xD.

```

Me interesé en escribir el presente manuscrito por 2 razones. La primera, para guiar a estudiantes o profesionales en como planear un proyecto de investigación de una manera facil; y segundo, ya que mientras escribia mi proyecto para el doctorado y organizaba información de varios años de los experimentos que realizamos, me pasé días organizando bases de datos de diversos estudiantes que ayudaron en la colecta de la información, y más que organizar, pareciera que estoy tratano de descifrar jeroglíficos, y solo él que colectó la información sabe lo que significa, lo que consume mucho tiempo y es cansativo.

Con frecuencia estudiantes me escriben, ya que tienen dudas para iniciar su proyecto de investigación o dar forma a un idea, y me hacen mutiples preguntas y afirmaciones, tales como: Cómo planteo mi proyecto de investigación?, Qué tipo de análisis debo usar?, mi asesor no tiene tiempo para ayudarme, no se como iniciar mi trabajo, estoy perdido ingeniero, etc...  y la verdad me gustaria ayudar a cada uno de ellos de forma personalizada, pero muchas veces no cuento con el tiempo suficiente para hacerlo. 

Uno de mis mentores durante mis prácticas profesionales, a quien recuerdo siempre, el Ing. Raúl Eyzaguirre me dijo en algun momento: "El proceso de investigación tiene muchos errores durante su ejecución, pero mismo así la ciencia siempre avanza." ironizando la forma en como muchos investigadores hacen ciencia y los problemas que tienen que resolver los que analizan la información al final de las investigaciones. O cuando algun investigador venia a su oficina con una base de datos y le decia "Por favor, haz todo los analisis necesario para este trabajo" sin si quiera ellos mismos saber cual es el objetivo, interrogante y/o hipotesis que desean responder con su investigación. Este tipo de casos es muy comun entre muchos investigadores, que emprenden algo sin tener una idea clara de lo que estan buscando y tienen la esperanza de encontrar algo en el camino, lo que mi asesor de doctorado lo llamo: "fishing expedition" (Una investigación realizada con la esperanza, aunque no con el propósito declarado, de descubrir alguna información). Lo cual tampoco esta mal ya que muchas cosas se descubrierón por casualidad. 

Pero, en este manuscrito nos estamos centrados en la investigación como un proceso organizado y estructurado y no como algo que estemos realizando al azar. De esta forma, evitar problemas posteriones, como cuando en algun momento escuché por ahí: "Traer un trabajo de investigación culminado es como traer un cadaver, lo unico que puedo hacer es la autopsia y decirte que fue lo que sucedió", haciendo referencia a que muchas veces emprendemos una investigación sin una planificación o metodología adecuada que me permitiran responder las hipotesis de mi trabajo. Por lo que no es recomendable iniciar una trabajo investigación sin tener una idea clara de lo que deseamos encontrar, que a lo contrario de lo que pensamos nos puede llevar a una perdida de tiempo y recursos.

Ser investigador es un trabajo basado en la disciplina, perseverancia y deseo por la mejora continua; que se va ganando con el tiempo y la experiencia, y muchas veces se logra a base de prueba y error (horrores tambien xD), así que no te sientas aturdido o decepcionados si recien estas comenzando... recuerda, para que un árbol sea grande y fuerte en algun momento fue una pequeña semilla que tuvo que germinar, crescer y luchar contra muchas condiciones adversas.

Este manuscrito es un conjunto de recomendaciones, de acuerdo a mi experiencia, con el que deseo compatir ideas básica para el planeamiento y manejo de un trabajo de investigación con la concepcion de que un trabajo de investigación es un trabajo multidisciplinario y de equipo. Puede servir de guía a los que por primera vez esten desarrollando un trabajo de investigación o recomendaciones para los que ya tiene experiencia. Se harán uso herramientas modernas y de acceso gratuito que no dificulten su aplicación en cualquier ambito de investigación. 

La idea de este manuscrito se basó en el documento que mi asesor del doctorado compartió en algun comento conmigo [@kamoun2013GOHREP], el cual me parecio muy interesante y en referencia a este documento, lo traducí, hice modificaciones y lo amplié de acuerdo a mi experiencia. 

Trataré en este documento ser lo más breve y conciso. A traves de este documento tengo planeado mostrarles (ire escribiendo poco a poco): i) Como plantear una idea de investigación, ii) Como organizar la información de la investigación, iii) Uso de herramientas para la colecta de datos, y iv) Como organizar, presentar y redactar un documento técnico científico (tesis/artículo). Incluiré material como documentos, videos y links con información de los temas que se está desarrollando con explicaciones que permitiran fijar las ideas de una manera fácil y sencilla. 

Espero que este manuscrito sea de utilidad para los que lo lean y el autor esta dispuesto a recibir todo tipo de criticas (destructivas y constructivas), ya que la crítica es la base de la mejora continua :). 